version: "3"

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea-48083
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__HTTP_PORT=48083
      - GITEA__server__ROOT_URL=http://localhost:48083/
      - GITEA__server__SSH_PORT=22
      - GITEA__server__DISABLE_SSH=true
      - GITEA__server__START_SSH_SERVER=false
      - GITEA__database__DB_TYPE=sqlite3
    restart: always
    volumes:
      - ~/docker-data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "48083:48083"  # 主机48083 → 容器48083
      - "222:22"       # SSH端口
    networks:
      - gitea

networks:
  gitea:
    external: false

